# Generated by Django 2.0.2 on 2020-06-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20200613_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
