# Generated by Django 2.0.2 on 2020-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='requirements',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
