# Generated by Django 2.0.2 on 2020-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200613_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='school',
            name='requirements',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=64),
        ),
    ]
